import { RoomType } from './types';

export interface RoomCatalogEntry {
  type: RoomType;
  label: string;
  defaultName: string;
  // ft defaults
  minWidth: number;
  minLength: number;
  preferredWidth: number;
  preferredLength: number;
  // color (hex) — blueprint navy family with accents per function
  color: string;
  accent: string;
  icon: string; // emoji-free; we'll map to lucide in UI by type
  group: 'private' | 'public' | 'service' | 'circulation';
  typical: boolean; // commonly requested
}

export const ROOM_CATALOG: Record<RoomType, RoomCatalogEntry> = {
  bedroom: {
    type: 'bedroom',
    label: 'Bedroom',
    defaultName: 'Bedroom',
    minWidth: 9,
    minLength: 10,
    preferredWidth: 12,
    preferredLength: 14,
    color: '#dbe7f3',
    accent: '#2b4a7a',
    icon: 'bed',
    group: 'private',
    typical: true,
  },
  bathroom: {
    type: 'bathroom',
    label: 'Bathroom',
    defaultName: 'Bathroom',
    minWidth: 5,
    minLength: 6,
    preferredWidth: 7,
    preferredLength: 8,
    color: '#d6e8ec',
    accent: '#2d6b78',
    icon: 'bath',
    group: 'service',
    typical: true,
  },
  kitchen: {
    type: 'kitchen',
    label: 'Kitchen',
    defaultName: 'Kitchen',
    minWidth: 8,
    minLength: 8,
    preferredWidth: 10,
    preferredLength: 10,
    color: '#fdeee0',
    accent: '#a85a1f',
    icon: 'chef-hat',
    group: 'service',
    typical: true,
  },
  living: {
    type: 'living',
    label: 'Living Room',
    defaultName: 'Living Room',
    minWidth: 12,
    minLength: 14,
    preferredWidth: 14,
    preferredLength: 16,
    color: '#e6efe0',
    accent: '#4a6b2a',
    icon: 'sofa',
    group: 'public',
    typical: true,
  },
  dining: {
    type: 'dining',
    label: 'Dining',
    defaultName: 'Dining',
    minWidth: 8,
    minLength: 10,
    preferredWidth: 10,
    preferredLength: 12,
    color: '#ece7da',
    accent: '#7a6a2a',
    icon: 'utensils',
    group: 'public',
    typical: true,
  },
  parking: {
    type: 'parking',
    label: 'Parking',
    defaultName: 'Parking',
    minWidth: 9,
    minLength: 18,
    preferredWidth: 10,
    preferredLength: 20,
    color: '#e4e4e7',
    accent: '#52525b',
    icon: 'car',
    group: 'service',
    typical: true,
  },
  balcony: {
    type: 'balcony',
    label: 'Balcony',
    defaultName: 'Balcony',
    minWidth: 4,
    minLength: 6,
    preferredWidth: 5,
    preferredLength: 8,
    color: '#e3f2e8',
    accent: '#2a8f5a',
    icon: 'trees',
    group: 'public',
    typical: true,
  },
  pooja: {
    type: 'pooja',
    label: 'Pooja Room',
    defaultName: 'Pooja Room',
    minWidth: 4,
    minLength: 4,
    preferredWidth: 5,
    preferredLength: 6,
    color: '#fbe9d6',
    accent: '#a8631f',
    icon: 'flame',
    group: 'private',
    typical: true,
  },
  office: {
    type: 'office',
    label: 'Office',
    defaultName: 'Office',
    minWidth: 8,
    minLength: 8,
    preferredWidth: 10,
    preferredLength: 10,
    color: '#e6e7f2',
    accent: '#3b3b7a',
    icon: 'briefcase',
    group: 'private',
    typical: false,
  },
  utility: {
    type: 'utility',
    label: 'Utility',
    defaultName: 'Utility',
    minWidth: 5,
    minLength: 6,
    preferredWidth: 6,
    preferredLength: 8,
    color: '#ececec',
    accent: '#6b7280',
    icon: 'washing-machine',
    group: 'service',
    typical: false,
  },
  staircase: {
    type: 'staircase',
    label: 'Staircase',
    defaultName: 'Staircase',
    minWidth: 6,
    minLength: 10,
    preferredWidth: 7,
    preferredLength: 12,
    color: '#e2e8f0',
    accent: '#475569',
    icon: 'stairs',
    group: 'circulation',
    typical: true,
  },
  foyer: {
    type: 'foyer',
    label: 'Foyer',
    defaultName: 'Foyer',
    minWidth: 5,
    minLength: 5,
    preferredWidth: 6,
    preferredLength: 6,
    color: '#eef0f3',
    accent: '#52525b',
    icon: 'door-open',
    group: 'circulation',
    typical: false,
  },
  store: {
    type: 'store',
    label: 'Store',
    defaultName: 'Store',
    minWidth: 4,
    minLength: 4,
    preferredWidth: 5,
    preferredLength: 5,
    color: '#ececec',
    accent: '#6b7280',
    icon: 'package',
    group: 'service',
    typical: false,
  },
};

export const TYPICAL_ROOM_TYPES: RoomType[] = (Object.keys(ROOM_CATALOG) as RoomType[]).filter(
  (t) => ROOM_CATALOG[t].typical,
);

export const ALL_ROOM_TYPES: RoomType[] = Object.keys(ROOM_CATALOG) as RoomType[];
