import { ProjectConfig, ProjectTemplate } from './types';

export const TEMPLATES: ProjectTemplate[] = [
  {
    id: 'tpl-1bhk',
    category: 'residential',
    name: '1 BHK',
    description: 'Compact single-bedroom home for small plots.',
    plot: {
      width: 20,
      length: 30,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 1,
    style: 'modern',
    rooms: [
      mkRoom('bedroom', 'Bedroom', 1, 11, 13, 'high'),
      mkRoom('bathroom', 'Bathroom', 1, 6, 7, 'medium'),
      mkRoom('kitchen', 'Kitchen', 1, 8, 8, 'high'),
      mkRoom('living', 'Living Room', 1, 12, 14, 'high'),
    ],
    preview: [
      { type: 'living', w: 60, l: 50 },
      { type: 'bedroom', w: 40, l: 35 },
      { type: 'kitchen', w: 25, l: 20 },
      { type: 'bathroom', w: 15, l: 12 },
    ],
  },
  {
    id: 'tpl-2bhk',
    category: 'residential',
    name: '2 BHK',
    description: 'Two-bedroom home for a 30×40 plot.',
    plot: {
      width: 30,
      length: 40,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 1,
    style: 'modern',
    rooms: [
      mkRoom('bedroom', 'Bedroom', 2, 11, 13, 'high'),
      mkRoom('bathroom', 'Bathroom', 2, 7, 8, 'medium'),
      mkRoom('kitchen', 'Kitchen', 1, 10, 10, 'high'),
      mkRoom('living', 'Living Room', 1, 14, 16, 'high'),
      mkRoom('parking', 'Parking', 1, 10, 18, 'medium'),
    ],
    preview: [
      { type: 'living', w: 55, l: 45 },
      { type: 'bedroom', w: 35, l: 30 },
      { type: 'bedroom', w: 30, l: 25 },
      { type: 'kitchen', w: 22, l: 18 },
      { type: 'bathroom', w: 12, l: 10 },
      { type: 'parking', w: 25, l: 12 },
    ],
  },
  {
    id: 'tpl-3bhk',
    category: 'residential',
    name: '3 BHK',
    description: 'Three-bedroom family home on a standard plot.',
    plot: {
      width: 30,
      length: 40,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 2,
    style: 'modern',
    rooms: [
      mkRoom('bedroom', 'Bedroom', 3, 11, 13, 'high'),
      mkRoom('bathroom', 'Bathroom', 2, 7, 8, 'medium'),
      mkRoom('kitchen', 'Kitchen', 1, 10, 10, 'high'),
      mkRoom('living', 'Living Room', 1, 14, 16, 'high'),
      mkRoom('dining', 'Dining', 1, 10, 12, 'medium'),
      mkRoom('parking', 'Parking', 1, 10, 18, 'medium'),
      mkRoom('pooja', 'Pooja Room', 1, 5, 6, 'low'),
    ],
    preview: [
      { type: 'living', w: 50, l: 40 },
      { type: 'bedroom', w: 32, l: 28 },
      { type: 'bedroom', w: 28, l: 24 },
      { type: 'bedroom', w: 28, l: 24 },
      { type: 'kitchen', w: 20, l: 18 },
      { type: 'dining', w: 18, l: 16 },
      { type: 'parking', w: 24, l: 12 },
    ],
  },
  {
    id: 'tpl-4bhk',
    category: 'residential',
    name: '4 BHK',
    description: 'Spacious four-bedroom home for larger families.',
    plot: {
      width: 40,
      length: 50,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 2,
    style: 'contemporary',
    rooms: [
      mkRoom('bedroom', 'Bedroom', 4, 12, 14, 'high'),
      mkRoom('bathroom', 'Bathroom', 3, 7, 8, 'medium'),
      mkRoom('kitchen', 'Kitchen', 1, 11, 12, 'high'),
      mkRoom('living', 'Living Room', 1, 16, 18, 'high'),
      mkRoom('dining', 'Dining', 1, 11, 13, 'medium'),
      mkRoom('parking', 'Parking', 1, 10, 20, 'medium'),
      mkRoom('balcony', 'Balcony', 1, 5, 8, 'low'),
      mkRoom('office', 'Office', 1, 10, 10, 'low'),
    ],
    preview: [
      { type: 'living', w: 48, l: 40 },
      { type: 'bedroom', w: 30, l: 26 },
      { type: 'bedroom', w: 26, l: 22 },
      { type: 'kitchen', w: 20, l: 18 },
      { type: 'parking', w: 24, l: 12 },
    ],
  },
  {
    id: 'tpl-duplex',
    category: 'residential',
    name: 'Duplex',
    description: 'Two-storey duplex with internal staircase.',
    plot: {
      width: 25,
      length: 40,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 2,
    style: 'modern',
    rooms: [
      mkRoom('living', 'Living Room', 1, 14, 16, 'high'),
      mkRoom('kitchen', 'Kitchen', 1, 10, 10, 'high'),
      mkRoom('dining', 'Dining', 1, 10, 10, 'medium'),
      mkRoom('bedroom', 'Bedroom', 3, 11, 13, 'high'),
      mkRoom('bathroom', 'Bathroom', 2, 7, 8, 'medium'),
      mkRoom('parking', 'Parking', 1, 9, 18, 'medium'),
    ],
    preview: [
      { type: 'living', w: 50, l: 42 },
      { type: 'bedroom', w: 30, l: 26 },
      { type: 'kitchen', w: 22, l: 18 },
      { type: 'parking', w: 24, l: 12 },
    ],
  },
  {
    id: 'tpl-villa',
    category: 'residential',
    name: 'Villa',
    description: 'Premium villa with open plan and large living.',
    plot: {
      width: 50,
      length: 60,
      unit: 'ft',
      roadSide: 'south',
      northDirection: 0,
      setbackFront: 0,
      setbackRear: 0,
      setbackSides: 0,
    },
    floors: 2,
    style: 'luxury',
    rooms: [
      mkRoom('living', 'Living Room', 1, 18, 20, 'high'),
      mkRoom('dining', 'Dining', 1, 12, 14, 'medium'),
      mkRoom('kitchen', 'Kitchen', 1, 12, 12, 'high'),
      mkRoom('bedroom', 'Bedroom', 4, 13, 15, 'high'),
      mkRoom('bathroom', 'Bathroom', 4, 8, 8, 'medium'),
      mkRoom('parking', 'Parking', 1, 12, 20, 'medium'),
      mkRoom('balcony', 'Balcony', 2, 6, 10, 'low'),
      mkRoom('pooja', 'Pooja Room', 1, 6, 6, 'low'),
      mkRoom('office', 'Office', 1, 11, 12, 'low'),
    ],
    preview: [
      { type: 'living', w: 46, l: 38 },
      { type: 'bedroom', w: 30, l: 26 },
      { type: 'bedroom', w: 26, l: 22 },
      { type: 'kitchen', w: 22, l: 18 },
      { type: 'parking', w: 24, l: 12 },
    ],
  },
  {
    id: 'tpl-office',
    category: 'commercial',
    name: 'Small Office',
    description: 'Compact office with cabins and meeting room.',
    plot: { width: 30, length: 40, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'modern',
    rooms: [
      mkRoom('living', 'Reception', 1, 12, 10, 'high'),
      mkRoom('office', 'Cabin', 3, 10, 10, 'high'),
      mkRoom('living', 'Meeting Room', 1, 12, 12, 'medium'),
      mkRoom('bathroom', 'Bathroom', 2, 6, 7, 'medium'),
      mkRoom('parking', 'Parking', 1, 10, 18, 'medium'),
    ],
    preview: [
      { type: 'living', w: 40, l: 32 },
      { type: 'office', w: 28, l: 24 },
      { type: 'office', w: 26, l: 22 },
      { type: 'bathroom', w: 14, l: 12 },
    ],
  },
  {
    id: 'tpl-retail',
    category: 'commercial',
    name: 'Retail Shop',
    description: 'Single-storey retail unit with storage.',
    plot: { width: 20, length: 40, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'modern',
    rooms: [
      mkRoom('living', 'Showroom', 1, 18, 24, 'high'),
      mkRoom('store', 'Store', 1, 10, 12, 'medium'),
      mkRoom('bathroom', 'Bathroom', 1, 6, 7, 'low'),
    ],
    preview: [
      { type: 'living', w: 55, l: 45 },
      { type: 'store', w: 22, l: 18 },
      { type: 'bathroom', w: 14, l: 12 },
    ],
  },
  {
    id: 'tpl-cafe',
    category: 'commercial',
    name: 'Café',
    description: 'Café with seating, kitchen counter, and washroom.',
    plot: { width: 25, length: 35, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'contemporary',
    rooms: [
      mkRoom('living', 'Seating', 1, 16, 18, 'high'),
      mkRoom('kitchen', 'Kitchen', 1, 10, 10, 'high'),
      mkRoom('bathroom', 'Washroom', 1, 6, 7, 'medium'),
      mkRoom('store', 'Store', 1, 8, 8, 'low'),
    ],
    preview: [
      { type: 'living', w: 50, l: 40 },
      { type: 'kitchen', w: 24, l: 20 },
      { type: 'bathroom', w: 14, l: 12 },
      { type: 'store', w: 16, l: 14 },
    ],
  },
  {
    id: 'tpl-studio',
    category: 'commercial',
    name: 'Studio',
    description: 'Open studio with workspace and utility.',
    plot: { width: 20, length: 30, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'minimal',
    rooms: [
      mkRoom('living', 'Studio', 1, 16, 20, 'high'),
      mkRoom('bathroom', 'Bathroom', 1, 6, 7, 'medium'),
      mkRoom('utility', 'Utility', 1, 6, 8, 'low'),
    ],
    preview: [
      { type: 'living', w: 55, l: 50 },
      { type: 'bathroom', w: 16, l: 14 },
      { type: 'utility', w: 18, l: 16 },
    ],
  },
  {
    id: 'tpl-guest',
    category: 'other',
    name: 'Guest House',
    description: 'Guest house with two bedrooms and common area.',
    plot: { width: 30, length: 40, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'traditional',
    rooms: [
      mkRoom('living', 'Lobby', 1, 12, 12, 'high'),
      mkRoom('bedroom', 'Guest Room', 2, 11, 13, 'high'),
      mkRoom('bathroom', 'Bathroom', 2, 7, 8, 'medium'),
      mkRoom('kitchen', 'Kitchenette', 1, 8, 8, 'low'),
      mkRoom('parking', 'Parking', 1, 10, 18, 'medium'),
    ],
    preview: [
      { type: 'living', w: 40, l: 34 },
      { type: 'bedroom', w: 30, l: 26 },
      { type: 'bedroom', w: 28, l: 24 },
      { type: 'parking', w: 24, l: 12 },
    ],
  },
  {
    id: 'tpl-rental',
    category: 'other',
    name: 'Rental Unit',
    description: 'Compact 1 BHK rental unit.',
    plot: { width: 20, length: 30, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'minimal',
    rooms: [
      mkRoom('living', 'Living', 1, 11, 12, 'high'),
      mkRoom('bedroom', 'Bedroom', 1, 10, 11, 'high'),
      mkRoom('kitchen', 'Kitchen', 1, 7, 8, 'medium'),
      mkRoom('bathroom', 'Bathroom', 1, 6, 7, 'medium'),
    ],
    preview: [
      { type: 'living', w: 42, l: 36 },
      { type: 'bedroom', w: 32, l: 28 },
      { type: 'kitchen', w: 22, l: 18 },
      { type: 'bathroom', w: 14, l: 12 },
    ],
  },
  {
    id: 'tpl-workspace',
    category: 'other',
    name: 'Small Workspace',
    description: 'Co-working style small workspace.',
    plot: { width: 25, length: 35, unit: 'ft', roadSide: 'south', northDirection: 0, setbackFront: 0, setbackRear: 0, setbackSides: 0 },
    floors: 1,
    style: 'modern',
    rooms: [
      mkRoom('living', 'Open Desks', 1, 16, 18, 'high'),
      mkRoom('office', 'Meeting Room', 1, 10, 10, 'medium'),
      mkRoom('bathroom', 'Bathroom', 1, 6, 7, 'low'),
      mkRoom('utility', 'Pantry', 1, 6, 8, 'low'),
    ],
    preview: [
      { type: 'living', w: 50, l: 42 },
      { type: 'office', w: 28, l: 24 },
      { type: 'utility', w: 18, l: 16 },
      { type: 'bathroom', w: 14, l: 12 },
    ],
  },
];

function mkRoom(
  type: ProjectTemplate['preview'][0]['type'],
  name: string,
  count: number,
  pw: number,
  pl: number,
  priority: 'high' | 'medium' | 'low',
) {
  return {
    type,
    name,
    count,
    minWidth: Math.round(pw * 0.7),
    minLength: Math.round(pl * 0.7),
    preferredWidth: pw,
    preferredLength: pl,
    priority,
    attachedTo: null,
    preferredLocation: null,
  };
}

export function templateToConfig(t: ProjectTemplate): ProjectConfig {
  return {
    plot: t.plot,
    floors: t.floors,
    rooms: t.rooms,
    style: t.style,
    preferences: [],
    vastuEnabled: false,
    vastu: { entrance: null, kitchen: null, bedroom: null, pooja: null },
  };
}
